modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="communismbad"
version="1.0.0"
displayName="Collectivism Brews A Lack Of Sentience"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Laptop-O-Matic II, MCreator"

[[dependencies.communismbad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




